# Generated by Django 3.0.4 on 2020-11-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201121_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='justif',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='prime',
            name='state',
            field=models.CharField(choices=[('EN', 'En attent'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='EN', max_length=2),
        ),
    ]
