# Generated by Django 3.0.4 on 2020-11-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201121_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='justif',
            field=models.FileField(upload_to='justif'),
        ),
    ]
