# Generated by Django 3.0.4 on 2020-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201121_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='justif',
            field=models.ImageField(upload_to='justif'),
        ),
    ]
