# Generated by Django 3.0.4 on 2020-11-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20201121_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='state',
            field=models.CharField(choices=[('En attent', 'En attent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='En attent', max_length=10),
        ),
    ]
