# Generated by Django 3.0.4 on 2020-11-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20201121_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='justif',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
