# Generated by Django 3.0.4 on 2020-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201122_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='article',
            field=models.CharField(max_length=200),
        ),
    ]
