# Generated by Django 3.0.4 on 2020-11-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20201122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes_article', to='App.Article'),
        ),
    ]
